### ISSUE TITLE
コメントに配信URLがあれば消す

### ISSUE THREAD

**Issue by cutls** [KnzkDev/KnzkLive#58]
TLにコメントを流すときに、見てもらえるようにと思って配信のURLを書くこともありそうだけど
KnzkLiveの画面上やコメント一覧では消したほうがいいかも

**Comment by yuzulabo** [comment]
コメントごと？URLだけ?

というか配信者が別の配信枠とかリレー配信とかで意図的に流す場合もあるのでうーんという感じ

もし見辛いなら配信者のNGワード設定で live.knzk.me/watch を指定すれば消えそう

**Comment by cutls** [comment]
@yuzulabo 説明が適当すぎました。URL文字列だけです。
Live109の配信では文字列"live.knzk.me/watch_109"だけ見えなくするみたいな
他の配信のURLは有用でも自分の配信のURLは恐らく無用では…

**Comment by imbsky** [comment]
Feel free to continue to comment if you have concerns, but I’m closing this for now since it’s not a high priority request. Thanks for your contributions.
